export const blogDetail = [
    {
        id:1,
       title:"Meet sustainability innovators combating climate change in India",
       date:"5 May 2023",
       author:"Yash patel",
       authorDesignation:"Founder Of The Company",
       src:"/assets/home-7-img-1.jpg",
       mainContent:[{
        type:"image",
        content:"/assets/home_blog_1.jpg",

       }],
       description_first: "Virtual reality (VR) has become increasingly popular in recent years, and for good reason. It offers an immersive experience that allows users to feel like they are a part of another world. For those who are new to VR, it can be overwhelming and confusing. However, there are many blogs that offer an introduction to the world of virtual reality. These blogs cover everything from the basics of VR technology to the different types of headsets and controllers available. They also provide information on the best VR games and experiences to try out as well as tips on how to make the most out of your virtual reality experience. These blogs have a wealth of information on all things VR and have become go-to sources for those looking to learn more about this exciting technology. As virtual reality continues to grow in popularity, these blogs will undoubtedly continue to provide valuable insights into this ever-changing field.Following VR blogs is essential for enthusiasts, developers, and businesses alike. Enthusiasts can stay up-to-date with the latest VR trends, news, and product releases. They can also learn about the best VR games and experiences available on the market. For developers, keeping up with VR blogs is crucial to stay in touch with new technologies and industry changes that may impact their work. They can learn about new software updates, hardware advancements, and tips for developing immersive experiences. Businesses can also benefit greatly from following VR blogs as they can gain valuable insights into consumer trends and preferences in this rapidly evolving field. They can stay informed about new business opportunities related to virtual reality like training simulations or interactive marketing campaigns. Additionally, following top VR blogs provides a platform for networking within the industry. It allows enthusiasts, developers, and businesses to connect with each other and share their ideas or collaborate on projects. Overall, staying connected through top VR blogs is an essential part of being involved in this exciting industry. There are a plethora of VR blogs out there, but not all of them offer the same quality of content. For those who want to stay up-to-date on the latest VR technology and trends, it’s important to find blogs that offer in-depth reviews, news, and insights.",
       secondContent:[{
        type:"image",
        content:"/assets/home_blog_1.jpg",

       }],
        description_second: "Virtual reality (VR) has become increasingly popular in recent years, and for good reason. It offers an immersive experience that allows users to feel like they are a part of another world. For those who are new to VR, it can be overwhelming and confusing. However, there are many blogs that offer an introduction to the world of virtual reality. These blogs cover everything from the basics of VR technology to the different types of headsets and controllers available. They also provide information on the best VR games and experiences to try out as well as tips on how to make the most out of your virtual reality experience. These blogs have a wealth of information on all things VR and have become go-to sources for those looking to learn more about this exciting technology. As virtual reality continues to grow in popularity, these blogs will undoubtedly continue to provide valuable insights into this ever-changing field.Following VR blogs is essential for enthusiasts, developers, and businesses alike. Enthusiasts can stay up-to-date with the latest VR trends, news, and product releases. They can also learn about the best VR games and experiences available on the market. For developers, keeping up with VR blogs is crucial to stay in touch with new technologies and industry changes that may impact their work. They can learn about new software updates, hardware advancements, and tips for developing immersive experiences. Businesses can also benefit greatly from following VR blogs as they can gain valuable insights into consumer trends and preferences in this rapidly evolving field. They can stay informed about new business opportunities related to virtual reality like training simulations or interactive marketing campaigns. Additionally, following top VR blogs provides a platform for networking within the industry. It allows enthusiasts, developers, and businesses to connect with each other and share their ideas or collaborate on projects. Overall, staying connected through top VR blogs is an essential part of being involved in this exciting industry. There are a plethora of VR blogs out there, but not all of them offer the same quality of content. For those who want to stay up-to-date on the latest VR technology and trends, it’s important to find blogs that offer in-depth reviews, news, and insights.",
        description_third:"Virtual reality (VR) has become increasingly popular in recent years, and for good reason. It offers an immersive experience that allows users to feel like they are a part of another world. For those who are new to VR, it can be overwhelming and confusing. However, there are many blogs that offer an introduction to the world of virtual reality. These blogs cover everything from the basics of VR technology to the different types of headsets and controllers available. They also provide information on the best VR games and experiences to try out as well as tips on how to make the most out of your virtual reality experience. These blogs have a wealth of information on all things VR and have become go-to sources for those looking to learn more about this exciting technology. As virtual reality continues to grow in popularity, these blogs will undoubtedly continue to provide valuable insights into this ever-changing field.Following VR blogs is essential for enthusiasts, developers, and businesses alike.",
        description_fourth:"Virtual reality (VR) has become increasingly popular in recent years, and for good reason. It offers an immersive experience that allows users to feel like they are a part of another world. For those who are new to VR, it can be overwhelming and confusing. However, there are many blogs that offer an introduction to the world of virtual reality. These blogs cover everything from the basics of VR technology to the different types of headsets and controllers available. They also provide information on the best VR games and experiences to try out as well as tips on how to make the most out of your virtual reality experience. These blogs have a wealth of information on all things VR and have become go-to sources for those looking to learn more about this exciting technology. As virtual reality continues to grow in popularity, these blogs will undoubtedly continue to provide valuable insights into this ever-changing field.Following VR blogs is essential for enthusiasts, developers, and businesses alike.",
        description_fifth:"Virtual reality (VR) has become increasingly popular in recent years, and for good reason. It offers an immersive experience that allows users to feel like they are a part of another world. For those who are new to VR, it can be overwhelming and confusing. However, there are many blogs that offer an introduction to the world of virtual reality. These blogs cover everything from the basics of VR technology to the different types of headsets and controllers available. They also provide information on the best VR games and experiences to try out as well as tips on how to make the most out of your virtual reality experience. These blogs have a wealth of information on all things VR and have become go-to sources for those looking to learn more about this exciting technology. As virtual reality continues to grow in popularity, these blogs will undoubtedly continue to provide valuable insights into this ever-changing field.Following VR blogs is essential for enthusiasts, developers, and businesses alike.",
        thirdContent:[{
            type:"image",
            content:"/assets/home_blog_1.jpg",
    
           }],
    },
    {
        id:2,
        name: "Noteworthy technology acquisitions 2021",
        value:"right"
    },
    {
        id:3,
        name: "Noteworthy technology acquisitions 2021",
        value:"left"
    },
]